pipeline_name: "vd-1x8x14-validation"
n_events: 10
skip_events : 0
first_stage: 0
keep_last_hist_file: True
keep_last_art_file: False

stages:
  gen : "prodgenie_nu_dunevd10kt_1x8x14_3view_30deg.fcl"
  g4 : "standard_g4_dunevd10kt_1x8x14_3view_30deg.fcl"
  detsim: "standard_detsim_dunevd10kt_1x8x14_3view_30deg.fcl"
  reco1 : "standard_reco1_dunevd10kt_1x8x14_3view_30deg.fcl"
  reco2 : "standard_reco2_dunevd10kt_1x8x14_3view_30deg.fcl"
  anatree : "run_reco1_ana_dunevd_1x8x14.fcl"

sequence:
  - "gen"
  - "g4"
  - "detsim"
  - "reco1"
  - "reco2"
  - "anatree"

