pipeline_name: "vd_radbkg_1x8x14"
n_events: 5
skip_events : 0
first_stage: 0

keep_last_hist_file: True
keep_last_art_file: False

stages:
  gen : "prodbackground_radiological_decay0_dunevd10kt_1x8x14_3view_30deg.fcl"
  g4 : "supernova_g4_dunevd10kt_1x8x14_3view_30deg.fcl"

  detsim_pds: "detsim_dunevd10kt_1x8x14_3view_30deg_light_only.fcl"
  detsim_tpc:
    template: "detsim_dunevd10kt_1x8x14_3view_30deg_tpc_only_template.fcl"
    n_step: 112
    delete_intermediate_products: True
    last_step_products: 'move'

  tpg : "triggersim_tpg_vd_1x8x14.fcl"
  anatree : "triggerana_vd_1x8x14_simpleThr.fcl"

sequence:
  - "gen"
  - "g4"
  - "detsim_pds"
  - "detsim_tpc"
  - "tpg"
  - "anatree"

